### ISSUE TITLE
Carticamento dati su servizio solr

### ISSUE THREAD

**Issue by verrico75** [Dataninja/ckan-101#10]
non si caricano i dati di reuters:

docker-compose exec app python db.py
[nltk_data] Downloading package reuters to /root/nltk_data...
Traceback (most recent call last):
  File "/opt/app/db.py", line 15, in <module>
    for take_id in nltk.corpus.reuters.fileids()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/local/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

i log

solr_1  | 2022-10-18 10:35:20.683 INFO  (searcherExecutor-10-thread-1-processing-x:reuters) [   x:reuters] o.a.s.c.SolrCore [reuters] Registered new searcher Searcher@26f42dde[reuters] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
app_1   | [2022-10-18 10:35:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
app_1   | [2022-10-18 10:35:42 +0000] [7] [INFO] Worker exiting (pid: 7)
app_1   | [2022-10-18 10:35:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
app_1   | [2022-10-18 10:35:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
app_1   | [2022-10-18 10:35:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
app_1   | [2022-10-18 10:35:42 +0000] [10] [INFO] Worker exiting (pid: 10)
app_1   | [2022-10-18 10:35:42 +0000] [9] [INFO] Worker exiting (pid: 9)
app_1   | [2022-10-18 10:35:42 +0000] [8] [INFO] Worker exiting (pid: 8)
app_1   | [2022-10-18 10:35:42 +0000] [1] [WARNING] Worker with pid 9 was terminated due to signal 9
app_1   | [2022-10-18 10:35:42 +0000] [1] [WARNING] Worker with pid 7 was terminated due to signal 9
app_1   | [2022-10-18 10:35:42 +0000] [17] [INFO] Booting worker with pid: 17
app_1   | [2022-10-18 10:35:42 +0000] [1] [WARNING] Worker with pid 10 was terminated due to signal 9
app_1   | [2022-10-18 10:35:42 +0000] [18] [INFO] Booting worker with pid: 18
app_1   | [2022-10-18 10:35:43 +0000] [19] [INFO] Booting worker with pid: 19
app_1   | [2022-10-18 10:35:43 +0000] [20] [INFO] Booting worker with pid: 20
app_1   | [nltk_data] Downloading package reuters to /root/nltk_data...
app_1   | [nltk_data] Downloading package reuters to /root/nltk_data...
app_1   | [nltk_data] Downloading package reuters to /root/nltk_data...
app_1   | [nltk_data] Downloading package reuters to /root/nltk_data...

**Comment by verrico75** [comment]
ho modificato il Dockerfile con **FROM python:alpine3.16**
e adesso funziona
