### ISSUE TITLE
Problema caricamento dati in solr

### ISSUE THREAD

**Issue by verrico75** [Dataninja/ckan-101#11]
Si è presentato il problema di caricamento dei file in solr.
La web application non funziona.

**ckan-101/lab/tutorials/solr]
└─$ docker-compose exec app python db.py                                             
[nltk_data] Downloading package reuters to /root/nltk_data...
Traceback (most recent call last):
  File "/opt/app/db.py", line 15, in <module>
    for take_id in nltk.corpus.reuters.fileids()
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/local/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file**

**Comment by verrico75** [comment]
Ciao Alessio, come mi hai consigliato tu, era una questione di volume già presente come spiegato qui: **https://github.com/gunthercox/ChatterBot/issues/1754**

Eliminando il volume ripetendo la procedura di caricamento funziona tutto.

Grazie

**Comment by verrico75** [comment]
Ok ho provato il wokaround suggerito, ma dopo il docker-compose down e docker-compose up --build -d ottengo:

 docker-compose down

e rilancio docker-compose up --build -d e poi ricarico i dati con docker-compose exec app python db.py

[nltk_data] Downloading package reuters to /root/nltk_data...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource reuters not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('reuters')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/reuters.zip/reuters/

  Searched in:
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/db.py", line 15, in <module>
    for take_id in nltk.corpus.reuters.fileids()
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource reuters not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('reuters')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/reuters

  Searched in:
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
